using System.Text.Json.Serialization;
using Fluxify.Core;

namespace Fluxify.Dto.Users;

public record UserPrivate(
    int? AccentColor,
    string[] Acls,
    UserAuthenticatorTypes[] AuthenticatorTypes,
    [property: JsonPropertyName("avatar")] string? AvatarHash,
    int? AvatarColor,
    [property: JsonPropertyName("banner")] string? BannerHash,
    int? BannerColor,
    string? Bio,
    bool? Bot,
    string Discriminator,
    string? Email,
    bool? EmailBounced,
    PublicUserFlags Flags,
    string? GlobalName,
    bool? HasDismissedPremiumOnboarding,
    bool? HasEverPurchased,
    bool? HasUnreadGiftInventory,
    Snowflake Id,
    bool IsStaff,
    bool MfaEnabled,
    bool NsfwAllowed,
    string? PasswordLastChangedAt,
    UserPrivateResponsePendingBulkMessageDeletion? PendingBulkMessageDeletion,
    string? Phone,
    bool PremiumBadgeHidden,
    bool PremiumBadgeMasked,
    bool PremiumBadgeSequenceHidden,
    bool PremiumBadgeTimestampHidden,
    DateTimeOffset? PremiumBillingCycle,
    bool PremiumEnabledOverride,
    int? PremiumLifetimeSequence,
    bool PremiumPurchaseDisabled,
    DateTimeOffset? PremiumSince,
    UserPremiumTypes PremiumType,
    DateTimeOffset? PremiumUntil,
    bool? PremiumWillCancel,
    string? Pronouns,
    string[]? RequiredActions,
    bool? System,
    string[] Traits,
    int UnreadGiftInventoryCount,
    bool UsedMobileClient,
    string Username,
    bool Verified
);